### ISSUE TITLE
Rhapsodii change tracker 

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#125]
Hopefully it's OK for me to track these here.

Rhapsodii related issues that need fixing as of WFL 5.3b12:

- [x] _Settings_ icon on Main screen needs to be removed
- [x] _Favourites_ icon on Main screen needs to me repositioned
- [x] Home menu new item _Settings_ overlaps help menu item
- [x] _Exit To_ menu is ordered incorrectly
- [x] fix pos: _Downloads > Custom Covers_ button
- [x] fix width: _Startup / Mount SD only_ button
- [x] fix width: _GC / Devo Emu Memcard_ button
- [x] fix width: _Homebrew / Hide_ button 
- [x] fix width: _Adult Only_ button

**Comment by gingerbeardman** [comment]
https://gist.github.com/gingerbeardman/141bd5173757c1bfea688b80951541b1

**Comment by Fledge68** [comment]
i'm not sure whee hakaisha's been.  she must be very busy. or she's waiting for me to put out a new release.

**Comment by gingerbeardman** [comment]
Not to worry, these are small changes but if she wants to take over, whenever, then that's fine

**Comment by Hakaisha** [comment]
Thank you for this, gingerbeardman. I'm completely fine with this being here, if Fledge is. 

I've lost someone dear to me recently, and I have been very busy. If there are any small changes or tweaks that you (or anyone else) feel would help Rhapsodii be a better theme, and/or keep it up to date; please by all means feel free to share them with the community, and I will credit you if your changes are included in the next release.

**Comment by gingerbeardman** [comment]
My thoughts are with you @Hakaisha and thanks for your blessing. Changes will be "maintenance" only and good luck to you

**Comment by gingerbeardman** [comment]
All fixes done and more along the way!
